name: Build Node WebRTC with H264 on CentOS 7
on:
  push:
    branches:
    - develop-centos
jobs:
  Build-Node-WebRTC-Actions:
    runs-on: ubuntu-latest
    container: docker.io/wangjin252/develop-base-image:centos-7
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare Environment
        run: |
          yum install -y openssl openssl-devel
          yum groupinstall -y Development Tools
      - name: NodeJS Dependencies Install
        run: |
          npm install
      - name: Build Release
        run: |
          ./node_modules/.bin/ncmake rebuild -- -DGN_GEN_ARGS='proprietary_codecs=true ffmpeg_branding="Chrome"'
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Node WebRTC CentOS
          path: ./build/Release/wrtc.node
